/**
 * In-memory store for PDF attachments generated by calculateBudget tool.
 *
 * The tool stores the PDF here keyed by filename after generation.
 * The controller retrieves it after agent.generate() completes.
 *
 * Primary retrieval: takeLatest() — always returns the most recent PDF.
 * Since agent.generate() is awaited synchronously, any PDF stored during
 * that call belongs to the current request.
 */

interface PdfEntry {
  pdfBase64: string;
  filename: string;
  timestamp: number;
}

const store = new Map<string, PdfEntry>();

const MAX_AGE_MS = 5 * 60 * 1000; // 5 minutes

function cleanup() {
  const now = Date.now();
  for (const [key, entry] of store) {
    if (now - entry.timestamp > MAX_AGE_MS) {
      store.delete(key);
    }
  }
}

export const pdfStore = {
  set(filename: string, pdf: { pdfBase64: string; filename: string }) {
    cleanup();
    store.set(filename, { ...pdf, timestamp: Date.now() });
    console.log(`[pdfStore] stored PDF: ${filename} (${Math.round(pdf.pdfBase64.length / 1024)}KB)`);
  },

  /**
   * Takes the most recently stored PDF entry, regardless of key.
   * This is the primary retrieval method — no dependency on agent text or RequestContext.
   */
  takeLatest(): { pdfBase64: string; filename: string } | null {
    cleanup();
    if (store.size === 0) return null;

    let latestKey: string | null = null;
    let latestTs = 0;
    for (const [key, entry] of store) {
      if (entry.timestamp > latestTs) {
        latestTs = entry.timestamp;
        latestKey = key;
      }
    }

    if (!latestKey) return null;
    const entry = store.get(latestKey)!;
    store.delete(latestKey);
    console.log(`[pdfStore] takeLatest: ${entry.filename}`);
    return { pdfBase64: entry.pdfBase64, filename: entry.filename };
  },
};
