/**
 * In-memory store for PDF attachments generated by calculateBudget tool.
 *
 * Keyed by pdfRequestId (UUID) set by the controller in RequestContext.
 * The same RequestContext propagates orgId (proven to work through Mastra
 * delegation), so pdfRequestId propagates identically.
 *
 * Flow:
 *   Controller: generates pdfRequestId → puts in RequestContext
 *   Tool: reads pdfRequestId from context → stores PDF here
 *   Controller: retrieves PDF by the same pdfRequestId
 */

interface PdfEntry {
  pdfBase64: string;
  filename: string;
  timestamp: number;
}

const store = new Map<string, PdfEntry>();

const MAX_AGE_MS = 5 * 60 * 1000; // 5 minutes

function cleanup() {
  const now = Date.now();
  for (const [key, entry] of store) {
    if (now - entry.timestamp > MAX_AGE_MS) {
      store.delete(key);
    }
  }
}

export const pdfStore = {
  set(requestId: string, pdf: { pdfBase64: string; filename: string }) {
    cleanup();
    store.set(requestId, { ...pdf, timestamp: Date.now() });
    console.log(`[pdfStore] stored: ${pdf.filename} (key=${requestId.slice(0, 8)}, ${Math.round(pdf.pdfBase64.length / 1024)}KB)`);
  },

  take(requestId: string): { pdfBase64: string; filename: string } | null {
    const entry = store.get(requestId);
    if (!entry) {
      console.log(`[pdfStore] miss: key=${requestId.slice(0, 8)} (store size=${store.size})`);
      return null;
    }
    store.delete(requestId);
    console.log(`[pdfStore] retrieved: ${entry.filename} (key=${requestId.slice(0, 8)})`);
    return { pdfBase64: entry.pdfBase64, filename: entry.filename };
  },
};
